# Generated by Django 5.0.1 on 2024-03-01 11:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Title', max_length=200)),
                ('content', models.CharField(default='Content', max_length=1000)),
                ('name', models.CharField(default='Name', max_length=100)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.ImageField(default='', upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Banners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleline1', models.CharField(default='Title', max_length=200)),
                ('titleline2', models.CharField(default='Title', max_length=200)),
                ('subtitle', models.CharField(default='SubTitle', max_length=200)),
                ('description', models.CharField(default='Description', max_length=200)),
                ('buttontext', models.CharField(default='Button Text', max_length=200)),
                ('buttonhref', models.CharField(default='Button Href', max_length=200)),
                ('image', models.ImageField(default='', upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Formcontact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Name', max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
    ]
