# Generated by Django 5.0.1 on 2024-03-01 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_banners'),
    ]

    operations = [
        migrations.AddField(
            model_name='banners',
            name='buttonhref',
            field=models.CharField(default='Button Href', max_length=200),
        ),
        migrations.AddField(
            model_name='banners',
            name='buttontext',
            field=models.CharField(default='Button Text', max_length=200),
        ),
        migrations.AddField(
            model_name='banners',
            name='description',
            field=models.CharField(default='Description', max_length=200),
        ),
        migrations.AddField(
            model_name='banners',
            name='subtitle',
            field=models.CharField(default='SubTitle', max_length=200),
        ),
    ]
