# Generated by Django 5.0.1 on 2024-03-01 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0010_banners_buttonhref_banners_buttontext_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banners',
            old_name='title',
            new_name='titleline1',
        ),
        migrations.AddField(
            model_name='banners',
            name='titleline2',
            field=models.CharField(default='Title', max_length=200),
        ),
    ]
