# Generated by Django 5.0.1 on 2024-03-01 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0011_rename_title_banners_titleline1_banners_titleline2'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='youtubelink',
            field=models.CharField(default='', max_length=200),
        ),
    ]
