# Generated by Django 5.0.1 on 2024-03-02 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0012_article_youtubelink'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Formcontact',
        ),
    ]
